export interface Property {
  slug: string;
  name: string;
  city: string;
  location: string;
  price: string;
  period: string;
  rating: number;
  reviews: number;
  beds: number;
  baths: number;
  sqft: string;
  thumbnail: string;
  tag: string | null;
  images: string[];
  description: string;
  amenities: string[];
}

export const properties: Property[] = [
  // ─── LONDON (5) ───────────────────────────────────────────────
  {
    slug: "the-scholars-haven",
    name: "The Scholar's Haven",
    city: "London",
    location: "South Kensington, London",
    price: "£350",
    period: "per week",
    rating: 4.9,
    reviews: 128,
    beds: 1,
    baths: 1,
    sqft: "25m²",
    thumbnail: "/city/DWVlxMLXIYibGkfBbV73OMd7eMkK8J.jpg",
    tag: "Popular",
    images: [
      "/property/download%20(48).jpg",
      "/room%20scholars%20bed/download%20(20).jpg",
      "/bathroom/download%20(20).jpg",
      "/daining%20area/download%20(48).jpg",
    ],
    description:
      "A beautifully designed studio apartment in the heart of South Kensington, perfect for students seeking luxury and convenience. Located steps away from Imperial College London and world-class museums, this property offers a serene study environment with premium furnishings, high-speed Wi-Fi, and 24-hour security.",
    amenities: [
      "High-Speed Wi-Fi",
      "Study Desk & Chair",
      "En-suite Bathroom",
      "Fully Equipped Kitchen",
      "Dining Area",
      "Laundry Facilities",
      "Cycle Storage",
      "24/7 Security",
      "Common Lounge",
    ],
  },
  {
    slug: "victoria-hall-residence",
    name: "Victoria Hall Residence",
    city: "London",
    location: "Westminster, London",
    price: "£280",
    period: "per week",
    rating: 4.8,
    reviews: 96,
    beds: 2,
    baths: 1,
    sqft: "35m²",
    thumbnail: "/city/IjvLOKWwU6CyER7QTJ6nValt8Oq2r9.jpg",
    tag: "Best Value",
    images: [
      "/property/download%20(49).jpg",
      "/room%20scholars%20bed/download%20(21).jpg",
      "/bathroom/download%20(21).jpg",
      "/daining%20area/download%20(49).jpg",
    ],
    description:
      "A spacious two-bedroom residence in Westminster offering exceptional value for money. With stunning views of the London skyline and easy access to the River Thames, this property combines affordability with prime location. Features include a modern kitchen, comfortable living area, and excellent transport links.",
    amenities: [
      "High-Speed Wi-Fi",
      "Study Area",
      "Modern Kitchen",
      "Dining Area",
      "Living Room",
      "Laundry Facilities",
      "Bike Storage",
      "CCTV Security",
      "On-site Maintenance",
    ],
  },
  {
    slug: "kings-cross-studio",
    name: "King's Cross Studio",
    city: "London",
    location: "King's Cross, London",
    price: "£420",
    period: "per week",
    rating: 4.9,
    reviews: 74,
    beds: 1,
    baths: 1,
    sqft: "30m²",
    thumbnail: "/city/ilXaYPdKFUJJjiKrzmOClEPFEco9Tu.jpg",
    tag: "Premium",
    images: [
      "/property/download%20(50).jpg",
      "/room%20scholars%20bed/download%20(22).jpg",
      "/bathroom/download%20(22).jpg",
      "/daining%20area/download%20(50).jpg",
    ],
    description:
      "A premium studio in the vibrant King's Cross area, ideal for students who value style and connectivity. This meticulously designed space features floor-to-ceiling windows, a sleek modern bathroom, and a fully integrated kitchen. Minutes from King's Cross Station and Central Saint Martins.",
    amenities: [
      "High-Speed Wi-Fi",
      "Smart TV",
      "En-suite Bathroom",
      "Integrated Kitchen",
      "Dining Area",
      "Air Conditioning",
      "Secure Entry",
      "Concierge Service",
      "Rooftop Terrace",
    ],
  },
  {
    slug: "the-bridge-apartments",
    name: "The Bridge Apartments",
    city: "London",
    location: "Shoreditch, London",
    price: "£310",
    period: "per week",
    rating: 4.7,
    reviews: 112,
    beds: 2,
    baths: 2,
    sqft: "45m²",
    thumbnail: "/city/LjrjFnDTQGtNZvUGxBjO.jpeg",
    tag: null,
    images: [
      "/property/download%20(51).jpg",
      "/room%20scholars%20bed/download%20(23).jpg",
      "/bathroom/download%20(23).jpg",
      "/daining%20area/download%20(51).jpg",
    ],
    description:
      "A contemporary two-bedroom, two-bathroom apartment in the creative heart of Shoreditch. Perfect for sharing students who want space and style. The open-plan living area is bathed in natural light, with a modern kitchen, hardwood floors, and access to a private courtyard garden.",
    amenities: [
      "High-Speed Wi-Fi",
      "Open Plan Living",
      "Two Bathrooms",
      "Modern Kitchen",
      "Dining Area",
      "Courtyard Garden",
      "Storage Room",
      "Video Intercom",
      "Bike Parking",
    ],
  },
  {
    slug: "canary-wharf-tower",
    name: "Canary Wharf Tower",
    city: "London",
    location: "Canary Wharf, London",
    price: "£450",
    period: "per week",
    rating: 4.8,
    reviews: 89,
    beds: 1,
    baths: 1,
    sqft: "32m²",
    thumbnail: "/city/RudSyGkpGV8dlaGmI74VmK47by52Yr.jpg",
    tag: "Premium",
    images: [
      "/property/download%20(54).jpg",
      "/room%20scholars%20bed/download%20(6).jpg",
      "/bathroom/download%20(6).jpg",
      "/daining%20area/download%20(48).jpg",
    ],
    description:
      "A luxurious high-rise studio in Canary Wharf with panoramic city views. This premium property features floor-to-ceiling windows, a modern en-suite bathroom, and a sleek kitchenette. Enjoy access to the residents' gym, rooftop terrace, and 24-hour concierge service.",
    amenities: [
      "High-Speed Wi-Fi",
      "Panoramic Views",
      "En-suite Bathroom",
      "Modern Kitchenette",
      "Dining Area",
      "Rooftop Terrace",
      "Gym Access",
      "24/7 Concierge",
      "Secure Entry",
    ],
  },

  // ─── MANCHESTER (3) ───────────────────────────────────────────
  {
    slug: "manchester-central-house",
    name: "Manchester Central House",
    city: "Manchester",
    location: "City Centre, Manchester",
    price: "£220",
    period: "per week",
    rating: 4.6,
    reviews: 67,
    beds: 1,
    baths: 1,
    sqft: "28m²",
    thumbnail: "/city/2n9jptiUWdcGQIRljf6BVASB0sRKSD.jpg",
    tag: "Best Value",
    images: [
      "/property/download%20(55).jpg",
      "/room%20scholars%20bed/download%20(7).jpg",
      "/bathroom/download%20(7).jpg",
      "/daining%20area/download%20(49).jpg",
    ],
    description:
      "A stylish and affordable studio in the heart of Manchester city centre. Perfect for students at the University of Manchester and Manchester Metropolitan University, this property offers a comfortable study environment with modern furnishings and excellent transport links.",
    amenities: [
      "High-Speed Wi-Fi",
      "Study Area",
      "En-suite Bathroom",
      "Kitchenette",
      "Dining Area",
      "Laundry Facilities",
      "Cycle Storage",
      "CCTV Security",
      "Social Lounge",
    ],
  },
  {
    slug: "oxford-road-studios",
    name: "Oxford Road Studios",
    city: "Manchester",
    location: "Oxford Road, Manchester",
    price: "£190",
    period: "per week",
    rating: 4.5,
    reviews: 54,
    beds: 2,
    baths: 1,
    sqft: "38m²",
    thumbnail: "/city/Mtw4YPkytipMAKLbaFcDQTripdJ17e.jpg",
    tag: null,
    images: [
      "/property/download%20(56).jpg",
      "/room%20scholars%20bed/download%20(8).jpg",
      "/bathroom/download%20(8).jpg",
      "/daining%20area/download%20(50).jpg",
    ],
    description:
      "A spacious two-bedroom apartment on Oxford Road, ideal for sharing students. Just minutes from the university campuses, this property features a bright living area, modern kitchen, and excellent transport connections. Exceptional value for student living.",
    amenities: [
      "High-Speed Wi-Fi",
      "Shared Living Room",
      "Modern Kitchen",
      "Dining Area",
      "Study Desks",
      "Laundry Facilities",
      "Secure Entry",
      "Bike Storage",
      "On-site Maintenance",
    ],
  },
  {
    slug: "northern-quarter-loft",
    name: "Northern Quarter Loft",
    city: "Manchester",
    location: "Northern Quarter, Manchester",
    price: "£260",
    period: "per week",
    rating: 4.7,
    reviews: 43,
    beds: 1,
    baths: 1,
    sqft: "27m²",
    thumbnail: "/city/oebCqiwXX1EFCJKgIUPADF6osnw9Sh.jpg",
    tag: "Premium",
    images: [
      "/property/download%20(57).jpg",
      "/room%20scholars%20bed/download%20(9).jpg",
      "/bathroom/download%20(9).jpg",
      "/daining%20area/download%20(51).jpg",
    ],
    description:
      "A trendy loft-style studio in Manchester's iconic Northern Quarter. Exposed brick walls, hardwood floors, and large windows create a creative living space. Surrounded by independent cafes, vintage shops, and art galleries, this is the perfect home for the style-conscious student.",
    amenities: [
      "High-Speed Wi-Fi",
      "Smart TV",
      "En-suite Bathroom",
      "Integrated Kitchen",
      "Dining Area",
      "Air Conditioning",
      "Heated Floors",
      "Video Intercom",
      "Bike Parking",
    ],
  },

  // ─── BIRMINGHAM (2) ──────────────────────────────────────────
  {
    slug: "brindley-place-living",
    name: "Brindley Place Living",
    city: "Birmingham",
    location: "Brindley Place, Birmingham",
    price: "£200",
    period: "per week",
    rating: 4.6,
    reviews: 78,
    beds: 2,
    baths: 1,
    sqft: "36m²",
    thumbnail: "/city/4BbT7SaPhDewwlluvuT0FN3lwZpoHj.jpg",
    tag: "Best Value",
    images: [
      "/property/download%20(58).jpg",
      "/room%20scholars%20bed/download%20(10).jpg",
      "/bathroom/download%20(10).jpg",
      "/daining%20area/download%20(52).jpg",
    ],
    description:
      "A well-appointed two-bedroom apartment in Birmingham's vibrant Brindley Place. Overlooking the canal with stunning city views, this property offers spacious living areas, a modern kitchen, and easy access to Birmingham's universities and the city's best restaurants.",
    amenities: [
      "High-Speed Wi-Fi",
      "Open Plan Living",
      "Modern Kitchen",
      "Dining Area",
      "Canal Views",
      "Laundry Facilities",
      "Secure Parking",
      "CCTV Security",
      "On-site Gym",
    ],
  },
  {
    slug: "jewellery-quarter-studio",
    name: "Jewellery Quarter Studio",
    city: "Birmingham",
    location: "Jewellery Quarter, Birmingham",
    price: "£175",
    period: "per week",
    rating: 4.5,
    reviews: 61,
    beds: 1,
    baths: 1,
    sqft: "24m²",
    thumbnail: "/city/ogZpldm7zBgVrgDIENerSntlUMcX7L.jpg",
    tag: "Popular",
    images: [
      "/property/download%20(59).jpg",
      "/room%20scholars%20bed/download%20(11).jpg",
      "/bathroom/download%20(11).jpg",
      "/daining%20area/download%20(53).jpg",
    ],
    description:
      "A charming studio apartment in the historic Jewellery Quarter. This cosy yet modern space features original period details combined with contemporary fittings. Walking distance to Birmingham City University and the city centre, with excellent local amenities on your doorstep.",
    amenities: [
      "High-Speed Wi-Fi",
      "Study Desk",
      "En-suite Bathroom",
      "Compact Kitchen",
      "Dining Area",
      "Laundry Facilities",
      "Bike Storage",
      "Secure Entry",
      "Period Features",
    ],
  },

  // ─── LIVERPOOL (2) ───────────────────────────────────────────
  {
    slug: "albert-dock-residence",
    name: "Albert Dock Residence",
    city: "Liverpool",
    location: "Albert Dock, Liverpool",
    price: "£185",
    period: "per week",
    rating: 4.7,
    reviews: 45,
    beds: 2,
    baths: 2,
    sqft: "42m²",
    thumbnail: "/city/4PNF3wGb6JZwOoF14kfzAl8ESHwQ8V.jpg",
    tag: null,
    images: [
      "/property/download%20(60).jpg",
      "/room%20scholars%20bed/download%20(12).jpg",
      "/bathroom/download%20(12).jpg",
      "/daining%20area/download%20(54).jpg",
    ],
    description:
      "A stunning two-bedroom, two-bathroom apartment at Liverpool's iconic Albert Dock. With breathtaking waterfront views and UNESCO World Heritage surroundings, this property combines historic charm with modern luxury. Minutes from Liverpool John Moores University and LJMU.",
    amenities: [
      "High-Speed Wi-Fi",
      "Waterfront Views",
      "Two Bathrooms",
      "Modern Kitchen",
      "Dining Area",
      "Living Area",
      "Secure Parking",
      "24/7 Security",
      "Bike Storage",
    ],
  },
  {
    slug: "hope-street-halls",
    name: "Hope Street Halls",
    city: "Liverpool",
    location: "Hope Street, Liverpool",
    price: "£210",
    period: "per week",
    rating: 4.6,
    reviews: 52,
    beds: 3,
    baths: 1,
    sqft: "50m²",
    thumbnail: "/city/A2uMphXsfFbJuJg87xDOYZ5iDtr5ka.jpg",
    tag: "Best Value",
    images: [
      "/property/download%20(61).jpg",
      "/room%20scholars%20bed/download%20(13).jpg",
      "/bathroom/download%20(13).jpg",
      "/daining%20area/download%20(53).jpg",
    ],
    description:
      "A spacious three-bedroom student house on Liverpool's prestigious Hope Street. Located between the two magnificent cathedrals and surrounded by the city's best restaurants and cultural venues. Ideal for a group of friends wanting to live in the heart of the city.",
    amenities: [
      "High-Speed Wi-Fi",
      "Study Area",
      "Modern Kitchen",
      "Dining Area",
      "Living Room",
      "Garden Access",
      "Laundry Facilities",
      "Gas Central Heating",
      "Double Glazing",
    ],
  },

  // ─── LEEDS (2) ───────────────────────────────────────────────
  {
    slug: "leeds-city-square",
    name: "Leeds City Square",
    city: "Leeds",
    location: "City Square, Leeds",
    price: "£195",
    period: "per week",
    rating: 4.8,
    reviews: 73,
    beds: 1,
    baths: 1,
    sqft: "26m²",
    thumbnail: "/city/t7hnQLv2aSnoCYwN1mX6wLC0OuOhxu.jpg",
    tag: "Popular",
    images: [
      "/property/download%20(62).jpg",
      "/room%20scholars%20bed/download%20(14).jpg",
      "/bathroom/download%20(14).jpg",
      "/daining%20area/download%20(48).jpg",
    ],
    description:
      "A modern studio apartment in the heart of Leeds, overlooking City Square. This well-designed space offers everything a student needs, from a dedicated study area to a fully equipped kitchen. Steps from Leeds University, the Trinity Shopping Centre, and vibrant nightlife.",
    amenities: [
      "High-Speed Wi-Fi",
      "Study Desk",
      "En-suite Bathroom",
      "Kitchenette",
      "Dining Area",
      "City Views",
      "Laundry Facilities",
      "Secure Entry",
      "Resident Lounge",
    ],
  },
  {
    slug: "headingley-house",
    name: "Headingley House",
    city: "Leeds",
    location: "Headingley, Leeds",
    price: "£220",
    period: "per week",
    rating: 4.5,
    reviews: 38,
    beds: 3,
    baths: 2,
    sqft: "55m²",
    thumbnail: "/city/xiJdNdpM84694i6gwxjWfbAyd67DrX.jpg",
    tag: null,
    images: [
      "/property/download%20(63).jpg",
      "/room%20scholars%20bed/download%20(15).jpg",
      "/bathroom/download%20(15).jpg",
      "/daining%20area/download%20(49).jpg",
    ],
    description:
      "A generous three-bedroom, two-bathroom house in the popular Headingley area. Perfect for student groups, this property offers a large living and dining area, private garden, and off-street parking. Located near Headingley Stadium and Otley Run, with excellent bus links to campus.",
    amenities: [
      "High-Speed Wi-Fi",
      "Two Bathrooms",
      "Large Kitchen",
      "Living & Dining Area",
      "Private Garden",
      "Off-street Parking",
      "Gas Central Heating",
      "Bike Shed",
    ],
  },

  // ─── EDINBURGH (2) ───────────────────────────────────────────
  {
    slug: "old-town-flat",
    name: "Edinburgh Old Town Flat",
    city: "Edinburgh",
    location: "Old Town, Edinburgh",
    price: "£290",
    period: "per week",
    rating: 4.8,
    reviews: 91,
    beds: 2,
    baths: 1,
    sqft: "34m²",
    thumbnail: "/city/d06qx3rs8EFTAxe4xl7ci2PB5ptMpQ.jpg",
    tag: "Premium",
    images: [
      "/property/download%20(64).jpg",
      "/room%20scholars%20bed/download%20(16).jpg",
      "/bathroom/download%20(16).jpg",
      "/daining%20area/download%20(50).jpg",
    ],
    description:
      "A beautifully restored two-bedroom flat in Edinburgh's historic Old Town. Character features including original fireplace and sash windows blend seamlessly with modern amenities. Just a short walk to the University of Edinburgh, Edinburgh Castle, and the Royal Mile.",
    amenities: [
      "High-Speed Wi-Fi",
      "Study Area",
      "Modern Bathroom",
      "Fully Equipped Kitchen",
      "Dining Area",
      "Living Room",
      "Laundry Facilities",
      "Period Features",
      "Double Glazing",
    ],
  },
  {
    slug: "holyrood-student-residence",
    name: "Holyrood Student Residence",
    city: "Edinburgh",
    location: "Holyrood, Edinburgh",
    price: "£250",
    period: "per week",
    rating: 4.7,
    reviews: 67,
    beds: 1,
    baths: 1,
    sqft: "29m²",
    thumbnail: "/city/YQar98ldInDxC5aaia9JhOOEbNtLav.jpg",
    tag: "Popular",
    images: [
      "/property/download%20(65).jpg",
      "/room%20scholars%20bed/download%20(17).jpg",
      "/bathroom/download%20(17).jpg",
      "/daining%20area/download%20(51).jpg",
    ],
    description:
      "A premium studio residence near Holyrood Park and the Scottish Parliament. This modern property offers luxury student living with stunning views of Arthur's Seat. Features include a stylish en-suite bathroom, integrated kitchen, and access to a communal study lounge.",
    amenities: [
      "High-Speed Wi-Fi",
      "Smart TV",
      "En-suite Bathroom",
      "Integrated Kitchen",
      "Dining Area",
      "Study Lounge",
      "Laundry Facilities",
      "24/7 Security",
      "Arthur's Seat Views",
    ],
  },
];

export function getPropertyBySlug(slug: string): Property | undefined {
  return properties.find((p) => p.slug === slug);
}
